### ISSUE TITLE
Help with jaeger OTLP metrics 

### ISSUE THREAD

**Issue by roiar** [brunobat/quarkus-observability-demo#15]
Hello Bruno!
Hope you are doing well!

I am trying to explore micrometer integration with Quarkus
I used as bases the example from https://quarkus.io/guides/telemetry-micrometer-tutorial
Included dependency
`<dependency> <groupId>io.quarkiverse.micrometer.registry</groupId> <artifactId>quarkus-micrometer-registry-otlp</artifactId> <version>3.2.4</version> </dependency>`
 

In application.properties
`quarkus.micrometer.registry-enabled-default=true quarkus.micrometer.export.otlp.enabled=true quarkus.micrometer.export.otlp.get-enabled=true quarkus.micrometer.export.otlp.url=http://localhost:4318/v1/metrics`

In order to have monitor tab enabled on a local jaeger deployment I used the docker-compose from [here](https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor) Made also a small addition in port binding to have 4318 also available

Unfortunately the prime number metric is not presented on the monitor dashboard. Only Operations metrics of the application, regarding the latency, request rate etc...

Also http://localhost:4318/v1/metrics responds 404 page not found

Could you please help me?

Thanks in advance
Best Regards,
Roi Arapoglou

**Comment by brunobat** [comment]
Sure!
Some questions:
1. Which micrometer registry are you using to export your metrics?
2. http://localhost:4318 is the port for the HTTP protocol in the OTel Collector. The usual is using GRPC and port 4317.
3. What is the "prime number metric"? Is it a custom metric that you are creating in the code? Can you please provide a code snipet?
4. If you see "Operations metrics of the application, regarding the latency, request rate etc..." looks like you are already receiving data.

**Comment by roiar** [comment]
Inside pom
![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/69a3192d-d32c-4634-82fc-506ed28485f1)


I have taken the example from here for the counters
https://quarkus.io/guides/telemetry-micrometer-tutorial#add-a-counter


In Jaeger monitor tool I cannot see the code counters

![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/7f7f89f4-9266-446c-a84a-feb4a8896c37)

Inside Prometheus
![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/77586225-222d-4b07-b1ea-7de885c20d0e)

And when I am trying to search Prometheus counters 


![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/d261f6d2-2e28-4666-a854-727b2ff6fda3)

**Comment by brunobat** [comment]
There are multiple problems happening here.
Let's leave the counter problem for later and solve first the connection issues.
--
If you want to use an OTLP registry you must not use the `quarkus-micromenter-registry-prometheus`. I assume you want to send all your data to an OTLP Collector, right?
If that's the case, is the collector that should forward the data to prometheus... using scraping of the latest Prometheus that is able to receive push data from the collector.

**Comment by roiar** [comment]
Right I want to send data to OTLP Collector, I removed the Prometheus registry dependency. Now The http://localhost:8080/q/metrics responds 404 not found

Here are my docker instances 
![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/8a6611c4-e08b-4ebe-8e6c-10ca2f78f87c)


And here is my application properties setup 

![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/cb698b14-424f-4dac-8120-423a2493ef7c)
Also after a while there is a warning log

14:45:30 WARN  traceId=, parentId=, spanId=, sampled= [io.mi.re.ot.OtlpMeterRegistry] (otlp-metrics-publisher) Failed to publish metrics to OTLP receiver: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)

**Comment by brunobat** [comment]
Please check this project as a reference: https://github.com/brunobat/quarkus-observability-demo/tree/main/quarkus-observability-demo-full 
Please ignore everything Openshift related.
Also, this docker compose also as a reference: https://github.com/brunobat/quarkus-observability-demo/tree/main/docker-compose/basic_with_prometheus

**Comment by roiar** [comment]
Based on this docker compose the docker instances created are
![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/31b2d664-226c-447a-8395-8d7f3632f2ff)

Unfortunatelly the monitor tab in Jaeger is disabled
![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/33577dc9-16fe-4a8b-8649-882f5afbf1e2)
and still there are error logs 
![image](https://github.com/brunobat/quarkus-observability-demo/assets/12119778/ed6870b6-94e2-4ae6-8dd5-ee20885c6626)

**Comment by brunobat** [comment]
Mind that is you are using the configs I provided above, The metrics will show up on the logs. No idea why Jaeger UI is disabled. 
You will need to share your docker compose and Jaeger config.
otel-collector is the name of the machine... if all ports are shared on the local network, try `localhost` or `0.0.0.0`

**Comment by roiar** [comment]
I ran docker-compose up on folder https://github.com/brunobat/quarkus-observability-demo/tree/main/docker-compose/basic_with_prometheus

I suspect that it has to do with configs they refer [here](https://www.jaegertracing.io/docs/1.48/spm/#enabling-spm)

Could you please provide me with print screens where are the metrics printed and how do we query the Prometheus?

**Comment by brunobat** [comment]
As you can see on this line:
https://github.com/brunobat/quarkus-observability-demo/blob/b858978390cb6df813187e506122333b8667fcd9/docker-compose/basic_with_prometheus/otel-collector-config.yaml#L40
These will be sent to the colector log (see the container output log) and prometheus, if properly configured. Sorry, but you'll have to research the prometheus queries.
